set( NAME arucoMarker )
set( VERSION 0.1 )
set( TYPE EXECUTABLE )
set( OPTIONS CONSOLE TRUE )
set( DEPENDENCIES )
set( REQUIREMENTS )
set( CONAN_DEPS
    SIGHT_CONAN_BOOST
    SIGHT_CONAN_OPENCV
    SIGHT_CONAN_FFMPEG
    SIGHT_CONAN_QT
)