set( NAME fwItkIO )
set( VERSION 0.1 )
set( TYPE LIBRARY )
set( DEPENDENCIES fwCore fwData fwDataIO fwTools )
set( REQUIREMENTS  )
set( USE_PCH_FROM_TARGET pchData )
set( CONAN_DEPS
    SIGHT_CONAN_ITK
    SIGHT_CONAN_ZLIB
    SIGHT_CONAN_LIBJPEG-TURBO
)