stages:
  - lint
  - prebuild
  - build
  - deploy

.linux_before:
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  dependencies: []
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_MAXSIZE: "32G"
    CCACHE_COMPRESS: "1"
    CCACHE_SLOPPINESS: "include_file_ctime,pch_defines,time_macros,file_macro,system_headers"
    CCACHE_NOHASHDIR: "1"
    CCACHE_DIR: "/cache/ccache"
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "ON"
    CC: "/usr/lib/ccache/gcc"
    CXX: "/usr/lib/ccache/g++"
  before_script:
    # Prepare sight source
    - sudo chown -R sight:sight .
    - mkdir -p $CI_PROJECT_DIR/.install $CI_PROJECT_DIR/.build
    # git configuration
    - git config merge.renameLimit 999999
    - git config user.name ${GITLAB_USER_ID}
    - git config user.email ${GITLAB_USER_EMAIL}
    - git config advice.addIgnoredFile false
    # Merge the MR branch into dev.
    - >
      if [ -z "$CI_COMMIT_TAG" ] && [ "$CI_COMMIT_REF_NAME" != "dev" ] && [ "$CI_COMMIT_REF_NAME" != "master" ]; then
        git fetch --all
        git checkout dev
        git reset --hard origin/dev
        git merge "origin/"${CI_COMMIT_REF_NAME} --no-commit --no-ff
        export EXTRA_BRANCH="dev"
      else
        export EXTRA_BRANCH="${CI_COMMIT_REF_NAME}"
      fi
    # Reset the modified time of all files to improve ccache performance
    - /usr/lib/git-core/git-restore-mtime --force --skip-missing --commit-time

lint:sheldon:
  extends: .linux_before
  dependencies: []
  stage: lint
  script:
    # Download sheldon.
    # TODO: use dev/master/tag branch
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ihu-strasbourg.eu/Sight/sight-git.git -b ${EXTRA_BRANCH} $CI_PROJECT_DIR/.build/sight-git
    # Stage all files from the merge to get them checked by sheldon.
    - git add *
    # Display modified files.
    - git status
    # Run sheldon on the merge result.
    - .build/sight-git/hooks/sheldon
  except:
    - dev
    - master
    - tags

.linux_build:
  extends: .linux_before
  dependencies: []
  stage: build
  script:
    # Print CCache statistics
    - ccache -s
    # Launch CMake
    - cd $CI_PROJECT_DIR/.build
    - >
      cmake $CI_PROJECT_DIR
      -G Ninja
      -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/.install
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DSIGHT_BUILD_TESTS=ON
      -DSIGHT_BUILD_DOC=${SIGHT_BUILD_DOC}
      -DSIGHT_ENABLE_PCH=OFF
      -DSIGHT_DEPS_ROOT_DIRECTORY=/cache/.sight-deps
      -DSIGHT_ENABLE_OPENVSLAM=ON
    # Touch all generated files to improve CCache performance
    - find . -type f -iname '*.?pp' -exec touch -t 197001010000 {} \;
    # Build
    - ninja
    # Print CCache statistics (Cache hit rate should have raised)
    - ccache -s
    # Clone sight-data.
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ihu-strasbourg.eu/Sight/sight-data.git -b ${EXTRA_BRANCH}
    - export FWTEST_DATA_DIR=$CI_PROJECT_DIR/.build/sight-data
    # Launch tests
    - ctest --timeout 480 --output-on-failure -O ctest.log -j4
    # Build documentation if needed
    - >
      if [ "${SIGHT_BUILD_DOC}" == "ON" ]; then
        ninja doc
      fi
    - >
      if [ "${SIGHT_BUILD_PACKAGE}" == "ON" ]; then
        ninja SightViewer_package
        ninja install
        ninja package
      fi

  artifacts:
    when: always
    paths:
      - .build/ctest.log
      - .build/Documentation/Doxygen/
      - .build/SightViewer*.tar.zst
      - .build/packages/sight-*.tar.zst

build:linux-20.10-debug-gcc:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Debug"
    SIGHT_BUILD_DOC: "OFF"
    SIGHT_BUILD_PACKAGE: "ON"
    SIGHT_IGNORE_UNSTABLE_TESTS: 1
    CC: "/usr/lib/ccache/gcc"
    CXX: "/usr/lib/ccache/g++"

build:linux-20.10-release-gcc:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "ON"
    SIGHT_BUILD_PACKAGE: "ON"
    SIGHT_IGNORE_UNSTABLE_TESTS: 1
    CC: "/usr/lib/ccache/gcc"
    CXX: "/usr/lib/ccache/g++"

build:linux-20.10-release-clang:
  extends: .linux_build
  variables:
    BUILD_TYPE: "Release"
    SIGHT_BUILD_DOC: "OFF"
    SIGHT_BUILD_PACKAGE: "OFF"
    SIGHT_IGNORE_UNSTABLE_TESTS: 1
    CC: "/usr/lib/ccache/clang"
    CXX: "/usr/lib/ccache/clang++"

# build:linux-21.04-release-gcc:
#   extends: .linux_build
#   image: "${SIGHT_CI_UBUNTU21_04}:dev"
#   variables:
#     BUILD_TYPE: "Release"
#     SIGHT_BUILD_DOC: "OFF"
#     SIGHT_BUILD_PACKAGE: "OFF"
#     CC: "/usr/lib/ccache/gcc"
#     CXX: "/usr/lib/ccache/g++"

.linux_deploy:
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  variables:
    BUILD_TYPE: "Release"
  stage: deploy
  script: 
    - cd .build/
    - >
      if [ "$BUILD_TYPE" == "Release" ]; then
        package_name=$(ls -1 SightViewer*)
        if [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
          new_name=`echo "$package_name" | sed -e 's/-[0-9]*-[a-z0-9]*/-latest/g'`
          mv $package_name $new_name
          package_name=$new_name
        fi
        new_name=${package_name/-Release/}
        mv $package_name $new_name
        package_name=$new_name
      fi
    - cd packages
    - package_name=$(ls -1 sight-*)
    - >
      if [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
        new_name=`echo "$package_name" | sed -e 's/-[0-9]*-[a-z0-9]*/-latest/g'`
        mv $package_name $new_name
        package_name=$new_name
      fi
  artifacts:
    paths:
      - .build/SightViewer*.tar.zst
      - .build/packages/sight-*.tar.zst

deploy:linux-debug:
  extends: .linux_deploy
  dependencies:
    - build:linux-20.10-debug-gcc
  variables:
    BUILD_TYPE: "Debug"
  only:
    refs:
      - master
      - dev

deploy_manual:linux-debug:
  extends: .linux_deploy
  dependencies:
    - build:linux-20.10-debug-gcc
  variables:
    BUILD_TYPE: "Debug"
  when: manual

deploy:linux-release:
  extends: .linux_deploy
  dependencies:
    - build:linux-20.10-release-gcc
  variables:
    BUILD_TYPE: "Release"
  only:
    refs:
      - master
      - dev

deploy_manual:linux-release:
  extends: .linux_deploy
  dependencies:
    - build:linux-20.10-release-gcc
  variables:
    BUILD_TYPE: "Release"
  when: manual

pages:
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  stage: deploy
  dependencies:
    - build:linux-20.10-release-gcc
  script:
    - mv .build/Documentation/Doxygen/html/ public/
  artifacts:
    paths:
      - public
  only:
    - dev
